### ISSUE TITLE
Consider adding list of dependencies for example workflows

### ISSUE THREAD

**Issue by bparks13** [open-ephys/onix1-bonsai-docs#1]
For workflows that we are providing that require certain dependencies, we need to find some way of listing the dependencies that are required so the user is aware of what to install prior to copying/pasting into their workflow.

As an example, for the `BreakoutAnalogOutput` workflow, we have added a `ScalarBuffer` which comes from the `Bonsai.Dsp` package.

What is the best method for highlighting dependencies?
- Add an `Annotation` node, which can show the dependency attached to the specific node that requires it.
![image](https://github.com/user-attachments/assets/bc4c89ac-b138-44ca-a403-7b97b0aac3d9)
- Write in the documentation directly which dependencies are required by a workflow

**Comment by cjsha** [comment]
I think we should provide instructions to download all dependencies used in the docs repo on the [Bonsai Installation and Configuration](https://open-ephys.github.io/onix1-bonsai-docs/articles/getting-started/install-configure-bonsai.html#install-packages-in-bonsai) page. Then, wherever there is a tutorial or example workflow that uses a dependency, we point them to the Bonsai Installation and Configuration page. For example:

> Visit the [Bonsai Installation and Configuration](https://open-ephys.github.io/onix1-bonsai-docs/articles/getting-started/install-configure-bonsai.html#install-packages-in-bonsai) page to download and install the dependencies that might be required to run this workflow. 

As it is, our dependency list isn't too large (just three packages, Onix1, Commutator, and Bonsai.StarterPack). We might have to think .of a better solution for this in the future if our dependency list grows.

I think it's also worth considering an OpenEphys.StarterPack so there is only one package for users to download. I just made an issue #31 for this idea.

**Comment by jonnew** [comment]
Agree with @cjsha on this. Lets keep the dependencies for our examples within the three that are listed in the installation instructions and it becomes a non-issue.
