### ISSUE TITLE
ConfigureHeadstage64: OpticalStimulator and ElecitricalStimulator should have their own subheaders?

### ISSUE THREAD

**Issue by cjsha** [open-ephys/onix1-bonsai-docs#11]
OpticalStimulator and ElecitricalStimulator should have their own subheaders in the [ConfigureHeadstage64](https://open-ephys.github.io/onix1-bonsai-docs/api/OpenEphys.Onix1.ConfigureHeadstage64.html#properties)?

![image](https://github.com/user-attachments/assets/c807464d-4caa-4844-a227-909fe450cb06)

![image](https://github.com/user-attachments/assets/56903d64-cd5f-4743-b1cd-71d6eaf6b6c7)

**Comment by jonnew** [comment]
Yes, these should be treated like the other Configure<whatever> members of the class.
