### ISSUE TITLE
Show top-level enum summary and remarks on operator pages?

### ISSUE THREAD

**Issue by cjsha** [open-ephys/onix1-bonsai-docs#20]
![Screenshot 2024-08-09 164735](https://github.com/user-attachments/assets/4a3017d0-fdfa-4e04-942d-70c1b2c75d29)

The top-level summary and remarks for enums (underlined in red in the above screenshot) don't show up when enums are integrated into the page of the operator that utilizes that enum (demonstrated below).

![image](https://github.com/user-attachments/assets/8437d40a-46be-4887-8acd-e5dbd19542c4)

I don't really care too much to include it in our template, but I wanted to bring it up as a point of discussion to confirm it's ok not care too much about these particular summary and remarks.

I could integrate it like this:

![Screenshot 2024-08-09 165524](https://github.com/user-attachments/assets/5409ef69-2a38-469a-a41d-4c291844bcf6)

@jonnew @bparks13 @ChucklesOnGitHub are all tagged because they might want to voice an opinion here.

**Comment by bparks13** [comment]
I think I'm okay leaving it off of the operator page, there is a lot of information to fit in those tables and it's pretty much redundant information anyway.

**Comment by cjsha** [comment]
I agree with Brandon and since no one else has expressed an opinion, I'm closing this issue.
