### ISSUE TITLE
OpenEphys.Onix1.Design docs

### ISSUE THREAD

**Issue by cjsha** [open-ephys/onix1-bonsai-docs#38]
> I'm not convinced that hiding the Design library under the Other dropdown is the best. The GUI will be a huge part of the functionality for a lot of these operators, and I think it should be more visible. For Bonsai libraries, each namespace is at the top-most level (for example, see the [Bonsai.Design library](https://bonsai-rx.org/docs/api/Bonsai.Design.html)). This approach makes sense to me because the namespace is a top-level item, it is what differentiates the two libraries from each other.

_Originally posted by @bparks13 in https://github.com/open-ephys/onix1-bonsai-docs/issues/37#issuecomment-2297466163_

I don't know the relevance of this package's documentation to the user being able to use the full functionality of Open Ephys hardware. This will help decide if/when we should work on this. I intend this to be a meta-issue from which more issues can spawn.

**Comment by bparks13** [comment]
As per other discussions and PRs, we have settled on placing the GUI tutorials under the relevant headstage / aggregate operator page in the User Guide. This is specifically being targeted in #58, where the tutorial pages are also being placed under their respective operator. This stemmed from a larger discussion that what we are currently calling `Tutorials` are really more like device-specific guides.

`Tutorials` as a term should only apply to guides that are of a higher-order than a single headstage or aggregate operator. Examples would be how to synchronize data across multiple aggregates, how to verify that stimulation is occurring on the correct `RHS2116` channel, how to create a configuration chain from scratch for multiple devices, or troubleshooting a workflow (these last are also being developed and added as `Tutorials` in #58).
