### ISSUE TITLE
Remove unused and incorrectly named files

### ISSUE THREAD

**Issue by bparks13** [open-ephys/onix1-bonsai-docs#42]
Prior to the recent template changes, apidoc pages were used to override and provide additional {{conceptual}} documentation to pages, but now those files are not used (and are still named based on the original library name) so they currently serve no purpose. 

These extra files should be removed, and if we no longer need the apidoc folder that should be removed too.

**Comment by bparks13** [comment]
@cjsha do we still need the apidoc folder?

**Comment by cjsha** [comment]
No I don't think so. I honestly thought I had removed that with an earlier PR. Since you assigned yourself, feel free to delete them
