### ISSUE TITLE
Clean up README

### ISSUE THREAD

**Issue by bparks13** [open-ephys/onix1-bonsai-docs#43]
See the following line as an example ["that that", "completely successfully" => "complete successfully"].

https://github.com/open-ephys/onix1-bonsai-docs/blob/99a50ed0e87cd97da671ef89bc6605ec0e7ec29b/README.md?plain=1#L77

Check that no other errors exist.

**Comment by cjsha** [comment]
jonnew mentioned that we should add a note about how the source code is accessible in the docs repo as a submodule. I think this was a point of confusion for him at first. I forgot to add this when he said it to me.

**Comment by cjsha** [comment]
We should also add some notes about [a script for cleaning old files](https://github.com/open-ephys/onix1-bonsai-docs/issues/24) once that issue is resolved.
