### ISSUE TITLE
Integrate Neuropixels 2.0e GUI tutorial into the rest of the headstage tutorial

### ISSUE THREAD

**Issue by bparks13** [open-ephys/onix1-bonsai-docs#59]
With #58, headstage-specific tutorials are being moved under their respective operator tab in the User Guide. Additionally, the existing GUI tutorial for Neuropixels 2.0e is also being placed under the same operator tab. However, these are currently separate pages, despite the interconnected nature of the GUI and usage of the headstage. We do not expect people to utilize Neuropixels without also capitalizing on the usage of the GUI, so we should work on integrating the existing content into the more general user guide.

**Comment by cjsha** [comment]
I think the GUI reference being its own page is ok though. It contains so much content. With that said, I agree that discussing it in greater detail in the "Configuration" page is a good idea.
