### ISSUE TITLE
Consider adding a simple procedure about how to update the Bonsai library.

### ISSUE THREAD

**Issue by filcarv** [open-ephys/onix1-bonsai-docs#7]
The ONIX computers being shipped are installed with the latest library available during assembly, which may not necessarily mean that it's the latest available version when shipping (because there's a time difference between the computer's assembly and shipping that can be months).

If documentation about how to update exists, we will add a PDF file right on the computer's Desktop asking the user to update the libraries before start working. We would point to this procedure.

**Comment by bparks13** [comment]
In addition to a page on updating the library, maybe add a page on how to uninstall the old library if needed.

**Comment by jonnew** [comment]
I think the local vs. global install issue is handled to some degree in the admonition about portable vs. global installs of Bonsai. I do agree that installation instructions would be helpful.

**Comment by cjsha** [comment]
since jonnew made a new issue for bparks latest comment on this thread, I'm going to go ahead and close this one.
